authentication/urls.py
from django.urls import path
from . import views

app_name = 'authentication'

urlpatterns = [
    path('login/',views.login_view,name='login'),
    path('register/',views.register_view,name='register'),
    path('logout',views.logout_view,name='logout'),
]

projectorganiser/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('authentication.urls',namespace='authentication')),
    path('',include('projects_shown.urls',namespace='projects_shown')),
    path('show/', include('show_project.urls',namespace="show_project"))
]

show_project/urls.py
from django.urls import path
from . import views

app_name = 'show_project'

urlpatterns = [
    path("",views.index,name='index_show'),
    path("<str:project_token>/",views.project_room,name='show_project')
]

authentication/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
import random

class TokenField(models.CharField):
    description = "A formatted text field with the pattern XXXX-XXXX-XXXX-XXXX"

    
    def generate_token(self):
        letters = [
        'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 
        'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'W', 'X', 'Y', 'Z'
        ]
        result = ""
        for i in range(0,16):
            if i%4 == 0 and i != 0:
                result += "-"
            result += random.choice(letters)
        return result 

    

    def __init__(self, *args, **kwargs):
        kwargs['max_length'] = 20
        kwargs['unique'] = True
        super().__init__(*args, **kwargs)
        self.validators.append(self.validate_format)
    
    
    def validate_format(self, value):
        if len(value) != 19:
            raise ValidationError(f"{value} is not a valid token")
        parts = value.split('-')
        if len(parts) != 4:
            raise ValidationError(f"{value} is not a valid token")
        
        for part in parts:
            if len(part) != 4 or not part.isalpha() or not part.isupper():
                raise ValidationError(f"{value} is not a valid token")  

    
# Create your models here.
class Feature_note(models.Model):
    feature_note = models.CharField(max_length=256,blank=True,null=True)

class Feature(models.Model):
    feature_add = models.CharField(max_length=80)
    feature_done = models.BooleanField(default=False)
    feature_notes = models.ManyToManyField(Feature_note,blank=True)

    def __str__(self):
        return self.feature_add


class Project(models.Model):
    name = models.CharField(max_length=80)
    link = models.URLField()
    notes = models.TextField(blank=True)
    features = models.ManyToManyField(Feature, blank=True)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    is_done = models.BooleanField(default=False)
    token = TokenField()

    def __str__(self):
        return self.name

authentication/forms.py
from django import forms
from .models import Project
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length=40,label="Username",widget=forms.TextInput(attrs={
        'placeholder':'Username',
        'autocomplete':'off'
        }))

    password1 = forms.CharField(max_length=40,label='Password',widget=forms.TextInput(attrs={
        'placeholder':'Password',
        'autocomplete':'off',
        'type':'password',
    }))

    password2 = forms.CharField(max_length=40,label='Password Again',widget=forms.TextInput(attrs={
        'placeholder':'Password',
        'autocomplete':'off',
        'type':'password',
    }))

    class Meta:
        model = User
        fields = ('username','password1','password2')

authentication/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import login,logout,authenticate
from .forms import SignUpForm
from django.contrib import messages

# Create your views here.
def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('Username')
        password = request.POST.get('Password')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('projects_shown:index')
        else:
            messages.error(request,"Invalid username or password")

    return render(request,"authentication/login.html")

def register_view(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            return redirect('authentication:login')
    else:
        form = SignUpForm()
    return render(request,"authentication/register.html",{
        'form':form
    })

def logout_view(request):
    logout(request)
    return redirect("authentication:login")

authentication/templates/authentication/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'authentication/img/programmer-software-engineer-coder-software-developer-svgrepo-com.svg' %}">
    {% block title %}

    {% endblock title %}
</head>
<body>
    {% block body %}

    {% endblock body %}
</body>
</html>

authentication/templates/authentication/login.html
{% extends 'authentication/base.html' %}
{% load static %}

{% block title %}
<title>Login Page</title>
<link rel="stylesheet" href="{% static 'authentication/css/login.css' %}">
{% endblock %}

{% block body %}
<div class="all-login">
    <h2>Project Organiser</h2>
    <div class="login-container">
        <form method="post" class="login-form">
            {% csrf_token %}
            <input type="text" placeholder="Username" id="Username" name="Username" required autocomplete="off">
            <input type="password" placeholder="Password" id="Password" name="Password" required autocomplete="off">
            <button type="submit">Login</button>
        </form>
        <div class="links">
            <a href="{% url 'authentication:register' %}">Don't have an account? Register</a>
            <a href="{% url 'show_project:index_show' %}">See project with token</a>
        </div>
    </div>
</div>
{% endblock %}

authentication/templates/authentication/register.html
{% extends 'authentication/base.html' %}
{% load static %}

{% block title %}
<title>Register Page</title>
<link rel="stylesheet" href="{% static 'authentication/css/register.css' %}">
{% endblock %}


{% block body %}
<div class="all-register">
    <h2>Register</h2>
    <div class="register-container">
        <form method="post" class="register-form">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Register</button>
        </form>
        <div class="links">
            <a href="{% url 'authentication:login' %}">Have an account? Login</a>
        </div>
    </div>
</div>
{% endblock %}