authentication/urls.py
from django.urls import path
from . import views

app_name = 'authentication'

urlpatterns = [
    path('login/',views.login_view,name='login'),
    path('register/',views.register_view,name='register'),
    path('logout',views.logout_view,name='logout'),
]

projectorganiser/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('authentication.urls',namespace='authentication')),
    path('',include('projects_shown.urls',namespace='projects_shown')),
    path('show/', include('show_project.urls',namespace="show_project"))
]

projects_shown/urls.py
from django.urls import path
from . import views

app_name = 'projects_shown'

urlpatterns = [
    path("", views.index, name='index'),
    path("add/", views.add_project, name='add'),
    path("dones/", views.done_projects, name='dones'),
    path("project/<str:project_name>/sure/done/",views.finish,name="finish"),
    path("project/<str:project_name>/sure/", views.sure, name="sure"),
    path("project/<str:project_name>/features/<int:feature_id>/done", views.done_feature, name='feature_done'),
    path("project/<str:project_name>/features/<int:feature_id>/delete", views.delete_feature, name="feature_delete"),
    path("project/<str:project_name>/<str:feature>", views.add_feature, name="add_feature"),
    path("project/<str:project_name>/", views.text_add, name='add_text'),  
    path("project/<str:project_name>", views.project_room, name='projects'),
    path("done/<str:project_name>",views.done_show,name='done_show'),
    path("project/<str:project_name>/features/page/<int:feature_id>",views.feature_page,name="feature_page"),
]

show_project/urls.py
from django.urls import path
from . import views

app_name = 'show_project'

urlpatterns = [
    path("",views.index,name='index_show'),
    path("<str:project_token>/",views.project_room,name='show_project')
]

projects_shown/forms.py
from django import forms
from authentication.models import Project,Feature

class project_form(forms.ModelForm):
    class Meta:
        model = Project
        fields = {'link','notes','features'}

        widgets = {
            'link':forms.TextInput(attrs={'autocomplete':'off'}),
            'notes':forms.Textarea(attrs={'autocomplete':'off'}),
        }
        

class add_project_form(forms.ModelForm):
    class Meta:
        model = Project
        fields = ("name","link",'token')
        
        labels = {
            'name':'Project Name',
            'link':'Github Link'
        }

        widgets = {
            'name':forms.TextInput(attrs={'autocomplete':'off'}),
            'link':forms.TextInput(attrs={'autocomplete':'off'}),
            'token':forms.TextInput(attrs={'autocomplete':'off','placeholder':'XXXX-XXXX-XXXX-XXXX','id':'token-form'})
        }

class feature_add(forms.ModelForm):
    class Meta:
        model = Feature
        fields = {'feature_add'}

        widgets = {
            'feature_add':forms.TextInput(attrs={'autocomplete':'off'})
        }

class note_add(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['notes']
        widgets = {
            'notes': forms.Textarea(attrs={'autocomplete':'off'}),  
        }

class feature_add_detail(forms.ModelForm):
    class Meta:
        model = Feature
        fields = {'feature_notes'}
        widgets = {
            'feature_notes': forms.TextInput(attrs={
                'autocomplete':'off',
                'class':'feature_notes'
            })
        }

projects_shown/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .forms import project_form,add_project_form,feature_add,note_add,feature_add_detail
from django.contrib.auth.decorators import login_required
from authentication.models import Project,Feature
from django.shortcuts import get_object_or_404
from django.urls import reverse

# Create your views here.
@login_required
def index(request):
    user = request.user
    form = project_form()
    projects = Project.objects.filter(user=request.user,is_done=False)
    return render(request, 'projects_shown/index.html',{
        'form':form,
        'user':user,
        'projects':projects,
    })

@login_required
def project_room(request,project_name):
    project = get_object_or_404(Project,name=project_name)
    form =  project_form()
    features = project.features.filter(feature_done = False)
    features_done = project.features.filter(feature_done = True)
    feature_form = feature_add()
    return render(request, 'projects_shown/project.html',{
        'project':project,
        'form':form,
        'feature_form':feature_form,
        'features':features,
        'done_features':features_done,
    })

@login_required
def add_project(request):
    form = add_project_form()
    user = request.user
    if request.method == 'POST':
        form = add_project_form(request.POST)
        if form.is_valid():
            project = form.save(commit=False)
            project.user = user
            project.save()
            return redirect('projects_shown:index')
    return render(request, 'projects_shown/add.html',{
        'form':form,
    })

@login_required
def add_feature(request, project_name,feature):
    project = get_object_or_404(Project, name=project_name)
    Feature_form = feature_add()
    

    if request.method == 'POST':
        Feature_form = feature_add(request.POST)
        if Feature_form.is_valid():
            feature_name = Feature_form.cleaned_data['feature_add']
            new_feature = Feature_form.save(commit= False)
            new_feature.feature_add = feature_name
            new_feature.save()
            project.features.add(new_feature)
            return redirect('projects_shown:projects', project_name=project_name)
    else:
        feature_form = feature_add()

    return redirect('projects_shown:projects', project_name=project_name)

@login_required
def done_feature(request,project_name,feature_id):
    project = get_object_or_404(Project, name=project_name)
    feature = get_object_or_404(Feature, pk=feature_id)
    
    if request.method == 'POST':    
        feature.feature_done = True
        feature.save()

    return redirect('projects_shown:projects', project_name=project_name)

@login_required
def delete_feature(request, project_name,feature_id):
    project = get_object_or_404(Project, name = project_name)
    feature = get_object_or_404(Feature, pk = feature_id)

    if request.method == 'POST':
        feature.delete()    

    return redirect('projects_shown:projects', project_name=project_name)

@login_required
def text_add(request, project_name):
    project = get_object_or_404(Project, name=project_name)

    if request.method == 'POST':
        new_notes = request.POST.get('text-area', '') 
        project.notes = new_notes  
        project.save()  

        return redirect('projects_shown:projects', project_name=project_name)

    return redirect('projects_shown:projects', project_name=project_name)

@login_required
def done_projects(request):
    projects = Project.objects.filter(is_done = True)
    return render(request,"projects_shown/done.html",{
        'projects':projects
        })

@login_required
def sure(request,project_name):
    project = get_object_or_404(Project,name = project_name)
    return render(request,"projects_shown/sure.html",{
        'project':project
    })

@login_required
def finish(request,project_name):
    project = get_object_or_404(Project,name = project_name)
    project.is_done = True
    project.save()
    return redirect("projects_shown:index")

@login_required
def done_show(request,project_name):
    project = get_object_or_404(Project,name = project_name)
    features_done = project.features.filter(feature_done = True)
    return render(request,"projects_shown/done_project.html",{
        'project':project,
        'features':features_done,
    })

def feature_page(request,project_name,feature_id):
    feature = get_object_or_404(Feature,id=feature_id)
    project = get_object_or_404(Project,name=project_name)
    form = feature_add_detail()
    return render(request,"projects_shown/feature_page.html",{
        'feature':feature,
        'project':project,
        'form':form
    })



#feature_name = Feature_form.cleaned_data['feature_add']
#new_feature = Feature_form.save(commit= False)
#new_feature.feature_add = feature_name
#new_feature.save()
#project.features.add(new_feature)

projects_shown/templates/projects_shown/add.html
{% extends "authentication/base.html" %}
{% load static %}

{% block title %}
<title>Add</title>
<link rel="stylesheet" href="{% static 'projects_shown/css/add.css' %}">
{% endblock %}

{% block body %}

<div class="container">
    <h2 class="create-project-heading">Create Project</h2>
    <div class="register-container">
        <form method="post" class="register-form">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
</div>

<script src="{% static 'projects_shown/js/add.js' %}"></script>
{% endblock %}

projects_shown/templates/projects_shown/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/b461c2f143.js" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'authentication/img/programmer-software-engineer-coder-software-developer-svgrepo-com.svg' %}">
    
    {% block title %}

    {% endblock title %}
</head>
<body>
    {% block body %}

    {% endblock body %}
</body>
</html>

projects_shown/templates/projects_shown/done.html
{% extends "projects_shown/base.html" %}
{% load static %}

{% block title %}

<title>Done Projects</title>
<link rel="stylesheet" href="{% static 'projects_shown/css/done.css' %}">

{% endblock title %}



{% block body %}

<div class="user">
    <h3>{{ user.username }}</h3>
</div>

<h2>Done Projects</h2>

<div class="done_projects">
    <a href="{% url 'projects_shown:index' %}">Projects</a>
</div>

<div class="projects-all">
    
{% for p in projects %}


<div class="project-card">
    <a href="{% url 'projects_shown:done_show' project_name=p.name %}">{{forloop.counter}} - {{p.name}}</a>
</div>


{% endfor %}


{% endblock body %}

projects_shown/templates/projects_shown/done_project.html
{% extends 'projects_shown/base.html' %}
{% load static %}

{% block title %}

<title>{{project.name}} information</title>
<link rel="stylesheet" href="{% static 'projects_shown/css/done_project.css' %}">

{% endblock title %}


{% block body %}

<h1>{{ project.name }}</h1>
<h2><a href="{{ project.link }}" target="_blank">Link: {{ project.link }}</a></h2>
<h3>Token: {{ project.token }}</h3>

<div class="home-page">
    <a href="{% url 'projects_shown:index' %}"><i class="fa-solid fa-house"></i></a>
</div>


<h1 id="feature-h1">Features</h1>
<div class="feature_show">
    {% for f in features.all %}
            <div class="feature-item">
                <h2>{{forloop.counter}}-{{f}}</h2> 
            </div>
    {% endfor %}

</div>

<div class="notes">
    <h2>Notes</h2>
        <textarea class="text-area" name="text-area" readonly>{{ project.notes }}</textarea>
</div>



{% endblock body %}

projects_shown/templates/projects_shown/feature_page.html
{% extends "projects_shown/base.html" %} {% block title %}

<title>Feature page</title>

{% endblock title %} 

{% block body %}

<form method="post">
    <label for="feature_notes">Feature note add:&nbsp;</label>
    {{ form.feature_notes }}
    <button type="submit">+</button>
</form>

{% endblock body %}

projects_shown/templates/projects_shown/index.html
{% extends "projects_shown/base.html" %}
{% load static %}

{% block title %}
<title>Home page</title>
<link rel="stylesheet" href="{% static 'projects_shown/css/index.css' %}">
{% endblock title %}

{% block body %}
<div class="container">

    <div class="user">
        <i class="fa-regular fa-user fa-2x"></i>
        <h2>{{ user.username }}</h2>
    </div>

    <div class="header">
        <h2>Projects</h2>
    </div>
    <div class="project-links">
        <a href="{% url 'projects_shown:dones' %}">Done Projects</a>
        <a href="{% url 'show_project:index_show' %}">See Project</a>
    </div>
    <div class="add-button">
        <a href="{% url 'projects_shown:add' %}"><i class="fa-solid fa-plus"></i></a>
    </div>
    <div class="projects-all">
        {% for p in projects %}
        <div class="project-card">
            <a href="{% url 'projects_shown:projects' project_name=p.name %}">{{forloop.counter}} - {{p.name}}</a>
        </div>
        {% endfor %}
    </div>
    <div class="logout">
        <a href="{% url 'authentication:logout' %}"><i class="fa-solid fa-right-from-bracket fa-2x"></i></a>
    </div>
</div>
{% endblock body %}

projects_shown/templates/projects_shown/project.html
{% extends 'projects_shown/base.html' %}
{% load static %}

{% block title %}
<title>Project</title>
<link rel="stylesheet" href="{% static 'projects_shown/css/project.css' %}">
{% endblock title %}

{% block body %}
<div class="container">
    <div class="home-page">
        <a href="{% url 'projects_shown:index' %}"><i class="fa-solid fa-house fa-2x"></i></a>
    </div>

    <div class="project-header">
        <h2>{{ project.name }}</h2>
        <br>
        <h3>Token: {{ project.token }}</h3>
        <div class="link">
            <h3>Link: <a href="{{ project.link }}" target="_blank">{{ project.link }}</a></h3>
        </div>
    </div>

    <div class="main-content">
        <div class="notes">
            <h2>Notes</h2>
            <br>
            <form method="post" action="{% url 'projects_shown:add_text' project_name=project.name %}">
                {% csrf_token %}
                <textarea class="text-area" name="text-area">{{ project.notes }}</textarea>
                <br>
                <br>
                <div class="button-container">
                    <button type="submit" class="btn">Save</button>
                </div>
            </form>
        </div>
        
        <div class="features">
            <h2>Features</h2>
            <div class="adding">
                <form method="post" action="{% url 'projects_shown:add_feature' project_name=project.name feature=feature_form.feature_add.value %}">
                    {% csrf_token %}
                    {{ feature_form.feature_add }}
                    <button type="submit" class="done-btn-small">+</button>
                </form>
            </div>
            
            <div class="feature-list">
                {% for f in features.all %}
                {% if not f.feature_done %}
                <div class="feature-item">
                    <h3><a href="{% url 'projects_shown:feature_page' project_name=project.name feature_id=f.id %}">{{ forloop.counter }}-{{ f }}</a></h3>
                    <div class="utils">
                        <form method="post" action="{% url 'projects_shown:feature_done' project_name=project.name feature_id=f.id %}">
                            {% csrf_token %}
                            <button type="submit" class="done-btn">+</button>
                        </form>
                        <form method="post" action="{% url 'projects_shown:feature_delete' project_name=project.name feature_id=f.id %}">
                            {% csrf_token %}
                            <button type="submit" class="delete-btn"><i class="fa-solid fa-trash"></i></button>
                        </form>
                    </div>
                </div>
                {% endif %}
                {% endfor %}
            </div>
        </div>

        <div class="done-features">
            <h2 style="text-align: center;">Done Features</h2>
            <div class="done-feature-list">
                {% for df in done_features %}
                <h3>{{ forloop.counter }}-{{ df }}</h3>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="project-finished">
        <form method="post">
            {% csrf_token %}
            <a href="{% url 'projects_shown:sure' project_name=project.name %}" class="finish-a">Finish Project</a>
        </form>
    </div>
</div>
{% endblock body %}

projects_shown/templates/projects_shown/sure.html
{% extends "projects_shown/base.html" %}
{% load static %}

{% block title %}

<title>Are you sure</title>
<link rel="stylesheet" href="{% static 'projects_shown/css/sure.css' %}">

{% endblock title %}



{% block body %}

<h2>Are you sure</h2>

<form method="post">
    <a href="{% url 'projects_shown:finish' project_name=project.name%}" class="sure">Yes</a>
</form>

<a href="{% url 'projects_shown:projects' project_name=project.name %}" class="not-sure">No</a>

{% endblock body %}  