projectorganiser/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('authentication.urls',namespace='authentication')),
    path('',include('projects_shown.urls',namespace='projects_shown')),
    path('show/', include('show_project.urls',namespace="show_project"))
]

projects_shown/urls.py
from django.urls import path
from . import views

app_name = 'projects_shown'

urlpatterns = [
    path("", views.index, name='index'),
    path("add/", views.add_project, name='add'),
    path("dones/", views.done_projects, name='dones'),
    path("project/<str:project_name>/sure/done/",views.finish,name="finish"),
    path("project/<str:project_name>/sure/", views.sure, name="sure"),
    path("project/<str:project_name>/features/<int:feature_id>/done", views.done_feature, name='feature_done'),
    path("project/<str:project_name>/features/<int:feature_id>/delete", views.delete_feature, name="feature_delete"),
    path("project/<str:project_name>/<str:feature>", views.add_feature, name="add_feature"),
    path("project/<str:project_name>/", views.text_add, name='add_text'),  
    path("project/<str:project_name>", views.project_room, name='projects'),
    path("done/<str:project_name>",views.done_show,name='done_show'),
    path("project/<str:project_name>/features/page/<int:feature_id>",views.feature_page,name="feature_page"),
]

show_project/urls.py
from django.urls import path
from . import views

app_name = 'show_project'

urlpatterns = [
    path("",views.index,name='index_show'),
    path("<str:project_token>/",views.project_room,name='show_project')
]

show_project/models.py
from django.db import models

# Create your models here.

show_project/forms.py
from django import forms
from authentication.models import Project
from django.core.exceptions import ValidationError

class TokenField(forms.CharField):
    def __init__(self, *args, **kwargs):
        kwargs['max_length'] = 19
        super().__init__(*args, **kwargs)
        self.validators.append(self.validate_format)
        self.widget.attrs.update({'class': 'token-field'})

    def validate_format(self, value):
        if len(value) != 19:
            raise ValidationError(f"{value} is not a valid token")
        parts = value.split('-')
        if len(parts) != 4:
            raise ValidationError(f"{value} is not a valid token")

        for part in parts:
            if len(part) != 4 or not part.isalpha() or not part.isupper():
                raise ValidationError(f"{value} is not a valid token")

    def clean(self, value):
        value = super().clean(value)
        self.validate_format(value)
        return value

class SeeForm(forms.Form):
    token = TokenField()


    

show_project/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .forms import SeeForm
from authentication.models import Project
from django.core.exceptions import ValidationError

# Create your views here.
def index(request):
    form = SeeForm()
    if request.method == 'POST':
        form = SeeForm(request.POST)
        if form.is_valid():
            token = form.cleaned_data['token']
            try:
                project = Project.objects.get(token=token)
                return redirect('show_project:show_project', project_token=token)
            except Project.DoesNotExist:
                form = SeeForm() 
    return render(request, 'show_project/index.html', {
        'form': form
    })

def project_room(request, project_token):
    try:
        project = Project.objects.get(token=project_token)
        features = project.features.filter(feature_done=False)
        features_done = project.features.filter(feature_done=True)
        return render(request, 'show_project/project_room.html', {
            'project': project,
            'features': features,
            'done_features': features_done,
        })
    except Project.DoesNotExist:
        return redirect('show_project:index')

show_project/templates/show_project/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'authentication/img/programmer-software-engineer-coder-software-developer-svgrepo-com.svg' %}">
    {% block title %}

    {% endblock title %}
</head>
<body>
    {% block body %}

    {% endblock body %}
</body>
</html>

show_project/templates/show_project/index.html
{% extends "show_project/base.html" %}
{% load static %}

{% block title %}
<title>Token</title>
<link rel="stylesheet" href="{% static 'show_project/css/index.css' %}">
{% endblock title %}

{% block body %}

<div class="token-in">
    <h2>Enter Token</h2>
    <div class="token-container">
        {% if message %}
            <p>{{ message }}</p>
        {% endif %}
        <form method="post" class="token-form">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Search</button>
        </form>
        <a href="{% url 'projects_shown:index' %}">Have an account? Login</a>
    </div>
</div>
{% endblock body %}

show_project/templates/show_project/project_room.html
{% extends 'projects_shown/base.html' %}
{% load static %}

{% block title %}
<title>Project</title>
<link rel="stylesheet" href="{% static 'projects_shown/css/project.css' %}">
{% endblock title %}

{% block body %}
<div class="container">
    <div class="home-page">
        <a href="{% url 'projects_shown:index' %}"><i class="fa-solid fa-house fa-2x"></i></a>
    </div>

    <div class="project-header">
        <h2>{{ project.name }}</h2>
        <br>
        <h3>Token: {{ project.token }}</h3>
        <div class="link">
            <h3>Link: <a href="{{ project.link }}" target="_blank">{{ project.link }}</a></h3>
        </div>
    </div>

    <div class="main-content">
        <div class="notes">
            <h2>Notes</h2>
            <br>
            <form method="post">
                {% csrf_token %}
                <textarea class="text-area" name="text-area">{{ project.notes }}</textarea>
                <br>
                <br>
                <div class="button-container">
                </div>
            </form>
        </div>
        
        <div class="features">
            <h2>Features</h2>
            <div class="adding">
                <form method="post">
                    {% csrf_token %}
                    {{ feature_form.feature_add }}
                </form>
            </div>
            
            <div class="feature-list">
                {% for f in features.all %}
                {% if not f.feature_done %}
                <div class="feature-item">
                    <h3>{{ forloop.counter }}-{{ f }}</h3>
                    <div class="utils">
                        <form method="post">
                            {% csrf_token %}
                        </form>
                        <form method="post">    
                            {% csrf_token %}
                        </form>
                    </div>
                </div>
                {% endif %}
                {% endfor %}
            </div>
        </div>

        <div class="done-features">
            <h2>Done Features</h2>
            <div class="done-feature-list">
                {% for df in done_features %}
                <h3>{{ forloop.counter }}-{{ df }}</h3>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="project-finished">
        <form method="post">
            {% csrf_token %}
            {% if project.is_done %}
                <h2>This project is finished</h2>
            {% else %}
                <h2>This project is not finished</h2>
            {% endif %}
            </form>
    </div>
</div>
{% endblock body %}